Remove required to VMware.PowerCLI on psd1 file
Because all module are not yet compatible with PowerShell core, and you get following exception :
Exception: The VMware.ImageBuilder module is not currently supported on the Core edition of PowerShell.